// Banque de textes "maison" (H12): pas d'extraits protégés (scripts de films,
// etc.), seulement des phrases écrites pour le projet et des dictionnaires de
// mots courants FR/EN, dans le domaine public de fait (pas d'œuvre tierce).

export const SENTENCES_FR = [
  "Le clavier est l'instrument le plus utilisé et le moins maîtrisé de la classe.",
  "Chaque erreur corrigée rapidement vaut mieux qu'une bonne frappe tapée trop lentement.",
  "La régularité compte plus que la vitesse quand on commence à pratiquer.",
  "Un bon dactylographe regarde l'écran, jamais ses doigts sur le clavier.",
  "La classe de français pratique la frappe pendant que la neige tombe dehors.",
  "Taper vite sans précision ne sert à rien si le texte final est illisible.",
  "Les élèves les plus rapides ne sont pas toujours les plus précis.",
  "Un court échauffement avant la course améliore souvent les résultats.",
  "La position des mains détermine en grande partie la vitesse de frappe.",
  "Chaque semaine, la vitesse moyenne du groupe augmente un peu plus.",
  "Le silence de la classe pendant une course est presque toujours total.",
  "Personne n'aime perdre une course à cause d'une seule faute de frappe.",
  "Les touches les plus utilisées s'usent plus vite que les autres.",
  "Un ordinateur bien réglé fait toute la différence pendant une partie.",
  "La compétition amicale pousse les élèves à s'entraîner davantage.",
  "Le professeur chronomètre la course et annonce le gagnant à la fin.",
  "Les bots servent surtout à s'entraîner quand il manque des joueurs.",
  "La précision s'améliore beaucoup après quelques semaines de pratique.",
  "Beaucoup d'élèves découvrent qu'ils tapent plus vite qu'ils ne le pensaient.",
  "La dernière ligne du texte est toujours la plus attendue de la course.",
];

export const SENTENCES_EN = [
  "The keyboard is the most used and least mastered tool in the classroom.",
  "A mistake fixed quickly beats a correct letter typed far too slowly.",
  "Consistency matters more than raw speed when you are just starting out.",
  "A good typist watches the screen, never their fingers on the keyboard.",
  "The English class practices typing while the snow falls outside.",
  "Typing fast without accuracy is useless if the final text is unreadable.",
  "The fastest students are not always the most accurate ones.",
  "A short warm up before the race often improves the final results.",
  "Hand position largely determines how fast someone can type.",
  "Every week, the average speed of the group goes up a little more.",
  "The classroom is almost completely silent during a typing race.",
  "Nobody likes losing a race because of a single typo near the end.",
  "The most used keys wear out faster than all the others combined.",
  "A well configured computer makes a real difference during a match.",
  "Friendly competition pushes students to practice a little more often.",
  "The teacher times the race and announces the winner at the very end.",
  "Bots are mostly useful for practice when there are not enough players.",
  "Accuracy improves a lot after a few weeks of regular practice.",
  "Many students discover they can type faster than they first thought.",
  "The last line of the text is always the most anticipated of the race.",
];

export const WORDS_FR = [
  "temps",
  "classe",
  "clavier",
  "vitesse",
  "course",
  "erreur",
  "souris",
  "texte",
  "lobby",
  "bouton",
  "podium",
  "combo",
  "touche",
  "record",
  "niveau",
  "joueur",
  "chef",
  "invité",
  "compte",
  "profil",
  "stat",
  "précision",
  "pratique",
  "doigt",
  "ligne",
  "mot",
  "phrase",
  "école",
  "prof",
  "semaine",
  "matin",
  "midi",
  "soir",
  "ami",
  "équipe",
  "groupe",
  "lettre",
  "point",
  "virgule",
  "majuscule",
];

export const ACCENT_WORDS_FR = [
  "élève",
  "émoji",
  "été",
  "âge",
  "élégant",
  "forêt",
  "fenêtre",
  "déjà",
  "très",
  "après",
  "problème",
  "système",
  "numéro",
  "égal",
  "créer",
  "précision",
  "récupérer",
  "général",
  "héros",
  "théâtre",
  "île",
  "naïf",
  "où",
  "à",
  "ça",
  "français",
  "garçon",
  "reçu",
  "façon",
  "leçon",
  "début",
  "côté",
  "hôte",
  "contrôle",
  "même",
  "première",
  "dernière",
  "répétition",
  "clé",
  "café",
];

export const WORDS_EN = [
  "time",
  "class",
  "keyboard",
  "speed",
  "race",
  "error",
  "mouse",
  "text",
  "lobby",
  "button",
  "podium",
  "combo",
  "key",
  "record",
  "level",
  "player",
  "host",
  "guest",
  "account",
  "profile",
  "stat",
  "accuracy",
  "practice",
  "finger",
  "line",
  "word",
  "sentence",
  "school",
  "teacher",
  "week",
  "morning",
  "noon",
  "evening",
  "friend",
  "team",
  "group",
  "letter",
  "point",
  "comma",
  "capital",
];
